defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 2
  username: postgres
  password: postgres

development:
  <<: *defaults
  database: sinatra_app_db_dev
  host: localhost

test:
  <<: *defaults
  database: sinatra_app_db_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
